site_name: Scanr
site_description: Security-first dependency scanning CLI
repo_url: https://github.com/Open-Lab-s/Scanr
repo_name: Open-Lab-s/Scanr

theme:
  name: shadcn

nav:
  - Home: index.md

plugins:
  - search